version: '3.3'

services:
  apache:
    build:
      context: ./webserver/bin
    #image: 'php:7.3-apache'
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    container_name: webserver_apache
    restart: always
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      #- /var/www/html:/var/www/html
      #- /etc/apache2:/etc/apache2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db   
  db:
    container_name: mysql_server
    #command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      #- /opt/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    volumes: 
      - /sessions
  memcached:
    image: memcached:latest
    restart: always
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_CACHE_SIZE=64
    links:
      - apache
  redis:
    container_name: 'png-redis'
    image: redis:latest
    ports:
      - "6379:6379"
#networks:
#  dev-network:
#    driver: bridge
    
